### ISSUE TITLE
Installing on Laravel 10.3 x is giving some error

### ISSUE THREAD

**Issue by bipsdevs** [weprodev/LaraPanel#12]
Error
Class "WeProDev\LaraNav\Enum\NavLocationEnum" not found
` // laranav.nav    
'nav' => [
        // laranav.nav.SIDE_NAV
        NavLocationEnum::SIDE_NAV->value => [
            [                'title' => 'Dashboard',
                'type' => NavLinkTypeEnum::ROUTE->value,
                'url' => 'lp.dashboard.panel',
                'active' => true,`

**Comment by Mekaeil** [comment]
Hi @bipsdevs 
Thanks for your feedback, I'll have a look and let you know. 

Do you have laranav.php in your config file?! did you installed laranav in your local, can you try this command?
```
composer require weprodev/laranav
```
